### ISSUE TITLE
Upgrade to `helmet` 5.0.0 has caused CORS issues

### ISSUE THREAD

**Issue by jbrooksuk** [microlinkhq/unavatar#174]
@Kikobeats PR #173 seems to have caused a CORS issue. We're seeing broken avatars on our products.

_Originally posted by @jbrooksuk in https://github.com/microlinkhq/unavatar/issues/173#issuecomment-1006373454_

**Comment by driesvints** [comment]
https://github.com/microlinkhq/unavatar/pull/175

**Comment by Kikobeats** [comment]
@driesvints @jbrooksuk can you confirm is it now resolved?

At least https://laravel.io/ is loading fine now 🙂

**Comment by driesvints** [comment]
Hey @Kikobeats, for now I still see broken images and errors in the console (Chrome). I'll monitor it.

<img width="1582" alt="Screenshot 2022-01-06 at 11 32 57" src="https://user-images.githubusercontent.com/594614/148369480-a985a413-1538-4db2-99f0-b91ec3139768.png">

**Comment by Kikobeats** [comment]
@driesvints can you try with an incognito browser?

**Comment by driesvints** [comment]
I just wanted to came back that i seems resolved now 🙂 

Thanks!

**Comment by jbrooksuk** [comment]
All good, thanks!

**Comment by Kikobeats** [comment]
Thanks to you for reporting 🙂
