### ISSUE TITLE
Use fallback avatar in case fallback URL is not reachable

### ISSUE THREAD

**Issue by driesvints** [microlinkhq/unavatar#202]
For some reason I get a 500 error for the following url: https://unavatar.io/github/qmcclure?fallback=http%3A%2F%2F127.0.0.1%3A8000%2Fimages%2Flaravelio-icon-gray.svg

This is because I'm passing a development url for the fallback icon. I'm wondering if instead of the 500 error we could just show the default unavatar fallback?

<img width="699" alt="Screenshot 2022-09-26 at 22 24 14" src="https://user-images.githubusercontent.com/594614/192372945-07491058-7534-44ab-b2d8-e3da2fc3bc12.png">

**Comment by Kikobeats** [comment]
Hello, it's a nice suggestion.

Unfortunately, it can't be possible with the current implementation:

https://github.com/microlinkhq/unavatar/blob/6572e7ef451b159c7dbb9dcbb2c4dafddb675d52/src/send/index.js#L28

When an error occurred, the response stream is closed, so you can't write the fallback avatar as fallback value.

**Comment by Kikobeats** [comment]
What I can do is to ping the fallback URL before using it, so in case the fallback URL isn't reachable, the default fallback image can be used.

But I don't want to implement this for now, since that implies a less optimal solution than the current source code (and maybe this is just a nice to have suggesion?

**Comment by driesvints** [comment]
Thanks @Kikobeats, definitely understandable. I think the ping before continuing is a good idea but understand if you don't want to pursue it. I guess I'll live with the broken avatars in development for now 🙂  I actually hardcoded the production url for them for now. Not ideal but workable.
