### ISSUE TITLE
All providers return the default avatar

### ISSUE THREAD

**Issue by sergioalvz** [microlinkhq/unavatar#218]
Hey @Kikobeats 👋 

I noticed that [unavatar.io](https://unavatar.io/) stopped working a couple of days ago (see https://unavatar.io/jack for example). 

Running the service locally, I see the latest commit can't resolve most providers (they always return the default avatar). This is the commit where I see things start failing: b70fa083340182e3db2dd3328e34452601dee825. 

I tried debugging the problem but couldn't find the root cause yet.

Let me know if there is something I can do to help!

**Comment by Kikobeats** [comment]
oh, really sorry for that, I found the bug 🤦 
https://github.com/microlinkhq/unavatar/commit/af958b1915f31385e3d1a0a318d727b4a82280e1

Can you verify it's working fine for you now?

**Comment by sergioalvz** [comment]
Providers seem to be working now, but I think there is still a problem with the `fallback` option (always returning the default avatar instead). 

I'm getting some intermittent failures for some avatars (sometimes getting the right image, sometimes getting the default avatar), but this might be related to my caching rather than with unavatar (saying it just in case).

**Comment by Kikobeats** [comment]
@sergioalvz sorry for that; I removed express as dependency the last week and I broke some code because of that.

I've started adding some tests to ensure everything goes back to normal https://github.com/microlinkhq/unavatar/pull/220

This branch is currently deployed to production, so you should to start to see avatars resolved properly.

**Comment by sergioalvz** [comment]
Thank you! Things look fairly back to normal. I'm always requesting avatars with a fallback to `boringavatars.com` and still getting the default `unavatar`'s avatar sometimes, but it's looking good 🙌

**Comment by Kikobeats** [comment]
@sergioalvz I'm working in some improvements today to finally address all the issues 🙂
