### ISSUE TITLE
Looking up by email return default tiktok image

### ISSUE THREAD

**Issue by CyberFoxar** [microlinkhq/unavatar#252]
Weird, issue, but it seems looking up via email is broken ?

poking any of those urls `https://unavatar.io/omidnikrah@gmail.com`, `https://unavatar.io/cyberfroxar@gmail.com` returns a default tiktok image, despite the latter having a correct gravatar (`https://unavatar.io/gravatar/cyberfroxar@gmail.com`).

However, using the example url (`https://unavatar.io/sindresorhus@gmail.com`), returns a correct avatar.

Unsure how to diagnose this, tbh.

**Comment by danharrin** [comment]
Lol, was just about to bring this up, so weird

**Comment by Kikobeats** [comment]
I had to flushed cache; can you confirm it's working at your end? https://unavatar.io/cyberfroxar@gmail.com

**Comment by CyberFoxar** [comment]
Indeed it works !
Had to refresh my local cache, but it worked :)
