### ISSUE TITLE
Implement a banner art fetching option

### ISSUE THREAD

**Issue by sidney-eliot** [microlinkhq/unavatar#256]
Currently one can only get the avatar, but another option be added to fetch the banner art of the profile. For example Twitter, the structure is practically the same to the profile picture so adding that functionality wouldn't be to hard.

**Comment by Kikobeats** [comment]
It isn't the target of the project, sorry!

You can build your own data rules using Microlink, check this:
https://microlink.io/recipes/twitter

🙂
