### ISSUE TITLE
Whats the default source for username query

### ISSUE THREAD

**Issue by michmzr** [microlinkhq/unavatar#264]
Hey,

I would like to ask for default provider for quering image for username e.g `https://unavatar.io/kikobeats`

If its a twitter, then there is a problem for example - [https://unavatar.io/twitter/MichalMzr](https://unavatar.io/twitter/MichalMzr) . Its my profile https://twitter.com/MichalMzr
There is a probably bug in twitter profile provider, becouse its returning a empty image.

Uses project is calling a query by username and its returning a strange result - https://github.com/wesbos/awesome-uses/issues/1625

**Comment by Kikobeats** [comment]
Twitter is under wall - it's expected, it doesn't work.

I'm waiting to see if they revert the situation, if not we should to drop twitter integration since it's not going to work anymore.
