### ISSUE TITLE
gravatar avatar not updating

### ISSUE THREAD

**Issue by MAAK-2904** [microlinkhq/unavatar#292]
I changed my Gravatar avatar and it is still not updating in Unavatar
This can be from the CDN cache system

**Comment by Kikobeats** [comment]
What's the unavatar URL?

**Comment by MAAK-2904** [comment]
https://unavatar.io/gravatar/mahdiakbari2904@gmail.com
This the URL

**Comment by MAAK-2904** [comment]
> What's the unavatar URL?
https://unavatar.io/gravatar/mahdiakbari2904@gmail.com
This the URL

**Comment by MAAK-2904** [comment]
> What's the unavatar URL?

https://unavatar.io/gravatar/mahdiakbari2904@gmail.com
This the URL

**Comment by Kikobeats** [comment]
refreshed https://unavatar.io/gravatar/mahdiakbari2904@gmail.com 🙂

**Comment by MAAK-2904** [comment]
> refreshed https://unavatar.io/gravatar/mahdiakbari2904@gmail.com 🙂

Thanks for your help my friend 
Actually it’s still not refreshed

**Comment by Kikobeats** [comment]
The content is cached for 24hrs, so as soon as it expired it will be refresehd, be patient 🙂

**Comment by MAAK-2904** [comment]
> The content is cached for 24hrs, so as soon as it expired it will be refresehd, be patient 🙂

still has not changed :) 💔

**Comment by Kikobeats** [comment]
Did you verify the gravatar URL is returning the expected URL?

**Comment by MAAK-2904** [comment]
> Did you verify the gravatar URL is returning the expected URL?

actually, this is the gravatar direct avatar link using the same email md5 hash:
[https://gravatar.com/avatar/30ba60cd1351c0b517cdf4ab4a44202b](https://gravatar.com/avatar/30ba60cd1351c0b517cdf4ab4a44202b)
and this is what Unavatar is showing:
[https://unavatar.io/gravatar/mahdiakbari2904@gmail.com](https://unavatar.io/gravatar/mahdiakbari2904@gmail.com)

**Comment by Kikobeats** [comment]
It seems it's working 🙂

![CleanShot 2023-12-14 at 15 33 32@2x](https://github.com/microlinkhq/unavatar/assets/2096101/4f36dba2-90dd-4a7f-a7ab-52d80c51b76d)
