### ISSUE TITLE
tiktok default image in 404 case

### ISSUE THREAD

**Issue by grabowskiadrian** [microlinkhq/unavatar#293]
Unavatar returns a tiktok image even if the user does not exist.

This is a problem with tiktok provider.

You are checking:

`$('meta[property="og:image"]').attr('content')`

 on tiktok response. But this tag occurs with 404.

Examples:
https://www.tiktok.com/@invalid_user_i_think
https://unavatar.io/invalid_user_i_think?fallback=false -> returns tiktok image, should 404

**Comment by Kikobeats** [comment]
Hello, I'm not be able to reproduce this anymore in the last unavatar version

![CleanShot 2023-12-28 at 13 02 52@2x](https://github.com/microlinkhq/unavatar/assets/2096101/d7cd0c26-ec08-4de9-8c7b-e34ad9f0c850)

🙂
