### ISSUE TITLE
live service seems down? 

### ISSUE THREAD

**Issue by PhilETaylor** [microlinkhq/unavatar#302]
Currently all links like https://unavatar.io/phil@phil-taylor.com are 502 Bad Gateway (CloudFlare) 
![ScreenShot-2024-01-07-18 22 41](https://github.com/microlinkhq/unavatar/assets/400092/5d718879-ce5c-4efe-b33e-889f68767313)

**Comment by Kikobeats** [comment]
Thanks for notifying. It should be back to operational 🙂

**Comment by PhilETaylor** [comment]
Thanks - really appreciate your work - was not expecting a response on a Sunday evening, but thought you would like to be informed :)
