### ISSUE TITLE
Images not loading - 524 error.

### ISSUE THREAD

**Issue by CamKem** [microlinkhq/unavatar#332]
Hi, we utilise unavatar & have for sometime been using Gravatar as the last fallback on the end of the string, to display the Gravatar fallback image for users without a valid link on our site. This is seeded data, but shows the syntax we have been using:

https://unavatar.io/fpollich@example.net?fallback=https://gravatar.com/avatar/019a7efaccba86d185277f7d9972cc79f9a9386c902b5de03b12c478d86f431d?s=300

Until about 24 hours ago loading the question mark fallback avatar that Gravatar uses worked, but it has since stopped working & is now giving a 524 response and if accessed directly via the browser a cloud flare error page.

Has there been any changes in the service?

I tried changing it to the gravatar provider as per the unavatar docs, with the following syntax:

https://unavatar.io/gracie.borer@example.net?fallback=https://unavatar.io/gravatar/gracie.borer@example.net

It resulted in the same thing, the 524 error.

It's effecting new signups & users changing links on their profile in production.

Would appreciate any advice.

<img width="915" alt="Screenshot 2024-04-18 at 7 05 32 pm" src="https://github.com/microlinkhq/unavatar/assets/112100521/84b561f3-c5a9-4633-8aa1-9086d7bfa262">

<img width="965" alt="Screenshot 2024-04-18 at 7 09 17 pm" src="https://github.com/microlinkhq/unavatar/assets/112100521/c8c7a5fd-ae6d-429e-94bc-7174baaeb1e3">

**Comment by CamKem** [comment]
On further testing, it's actually not loading any images. Even ones that were loading fine yesterday, for all new users & all users changing their avatar.

**Comment by jchristy40** [comment]
I'm getting the same thing!

**Comment by AshesOfPhoenix** [comment]
I am facing the same problem as well.

**Comment by tk5446** [comment]
I am also getting this. Is anybody available to respond? thanks

**Comment by scottmetoyer** [comment]
We are having the same issue.

**Comment by Kikobeats** [comment]
Hello, thanks for reporting. The issue is identified and I'm working into fix it. It's expected to be fixed today, let me keep you posted 🙂

**Comment by Kikobeats** [comment]
Fixed after https://github.com/microlinkhq/unavatar/commit/df8481c667ac7983e000d67312358c36f2fcbea7.

I'm also implementing a new way to autoscale unavatar - https://twitter.com/Kikobeats/status/1782072643614597230

I need to do some live testing to fine-tune the settings, but I'm going to close for now since the traffic is back to stable. Thanks again for reporting!
