### ISSUE TITLE
Instagram profile picture does not work

### ISSUE THREAD

**Issue by BossElijah** [microlinkhq/unavatar#341]
The Instagram endpoint always returns unavatar's logo instead of actually getting the user's profile pic. Is there a way I can get it working?

See example: https://unavatar.io/instagram/annastalksme

**Comment by BossElijah** [comment]
Oops, I accidentally closed it - is there a way I can add labels to this issue?

**Comment by BossElijah** [comment]
@Kikobeats is this something youre aware of?

**Comment by Kikobeats** [comment]
I don't think there is much to do if Instagram decides to put the content behind a wall for IP that comes from data centers, we should to disable instagram for a while (we did the same for TikTok in the past)

**Comment by BossElijah** [comment]
Ok, thank you. Lmk when/if it gets up and working again!
